/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetDailySessionCountsParams,
  GetWeeklyCompletedSessionCountsParams,
  GetWeeklyMuscleGroupSetsParams,
  HTTPValidationError,
  WeeklyMuscleGroupSets,
  WorkoutSessionRead,
  WorkoutSessionStart,
  WorkoutSessionUpdate
} from '../../model';

import { customInstance } from '../../http-client';
import type { ErrorType } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Return the current user's workout sessions that haven't been completed yet.
 * @summary List active workout sessions
 */
export const listActiveWorkoutSessions = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead[]>(
      {url: `/api/v1/workout-sessions/active`, method: 'GET', signal
    },
      options);
    }




export const getListActiveWorkoutSessionsQueryKey = () => {
    return [
    `/api/v1/workout-sessions/active`
    ] as const;
    }


export const getListActiveWorkoutSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListActiveWorkoutSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listActiveWorkoutSessions>>> = ({ signal }) => listActiveWorkoutSessions(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListActiveWorkoutSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listActiveWorkoutSessions>>>
export type ListActiveWorkoutSessionsQueryError = ErrorType<unknown>


export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List active workout sessions
 */

export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListActiveWorkoutSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Return the current user's workout sessions that have been completed.
 * @summary List completed workout sessions
 */
export const listCompletedWorkoutSessions = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead[]>(
      {url: `/api/v1/workout-sessions/completed`, method: 'GET', signal
    },
      options);
    }




export const getListCompletedWorkoutSessionsQueryKey = () => {
    return [
    `/api/v1/workout-sessions/completed`
    ] as const;
    }


export const getListCompletedWorkoutSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompletedWorkoutSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>> = ({ signal }) => listCompletedWorkoutSessions(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCompletedWorkoutSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>>
export type ListCompletedWorkoutSessionsQueryError = ErrorType<unknown>


export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List completed workout sessions
 */

export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCompletedWorkoutSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Return how many sets were completed per muscle group in a Monday-to-Sunday week.
 * @summary Get completed sets per muscle group for a calendar week
 */
export const getWeeklyMuscleGroupSets = (
    params?: GetWeeklyMuscleGroupSetsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WeeklyMuscleGroupSets>(
      {url: `/api/v1/workout-sessions/weekly-sets`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetWeeklyMuscleGroupSetsQueryKey = (params?: GetWeeklyMuscleGroupSetsParams,) => {
    return [
    `/api/v1/workout-sessions/weekly-sets`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetWeeklyMuscleGroupSetsQueryOptions = <TData = Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError = ErrorType<HTTPValidationError>>(params?: GetWeeklyMuscleGroupSetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWeeklyMuscleGroupSetsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>> = ({ signal }) => getWeeklyMuscleGroupSets(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWeeklyMuscleGroupSetsQueryResult = NonNullable<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>>
export type GetWeeklyMuscleGroupSetsQueryError = ErrorType<HTTPValidationError>


export function useGetWeeklyMuscleGroupSets<TData = Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetWeeklyMuscleGroupSetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklyMuscleGroupSets<TData = Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetWeeklyMuscleGroupSetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklyMuscleGroupSets<TData = Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetWeeklyMuscleGroupSetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get completed sets per muscle group for a calendar week
 */

export function useGetWeeklyMuscleGroupSets<TData = Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetWeeklyMuscleGroupSetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyMuscleGroupSets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWeeklyMuscleGroupSetsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Return the current user's session counts per day, grouped into Monday-to-Sunday weeks.
 *
 * Weeks are ordered oldest first; the current week only runs up to today.
 * @summary Get the number of workout sessions per day over recent calendar weeks
 */
export const getDailySessionCounts = (
    params?: GetDailySessionCountsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<number[][]>(
      {url: `/api/v1/workout-sessions/daily-counts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetDailySessionCountsQueryKey = (params?: GetDailySessionCountsParams,) => {
    return [
    `/api/v1/workout-sessions/daily-counts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDailySessionCountsQueryOptions = <TData = Awaited<ReturnType<typeof getDailySessionCounts>>, TError = ErrorType<HTTPValidationError>>(params?: GetDailySessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySessionCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDailySessionCountsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailySessionCounts>>> = ({ signal }) => getDailySessionCounts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDailySessionCounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDailySessionCountsQueryResult = NonNullable<Awaited<ReturnType<typeof getDailySessionCounts>>>
export type GetDailySessionCountsQueryError = ErrorType<HTTPValidationError>


export function useGetDailySessionCounts<TData = Awaited<ReturnType<typeof getDailySessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetDailySessionCountsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySessionCounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailySessionCounts>>,
          TError,
          Awaited<ReturnType<typeof getDailySessionCounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDailySessionCounts<TData = Awaited<ReturnType<typeof getDailySessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetDailySessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySessionCounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailySessionCounts>>,
          TError,
          Awaited<ReturnType<typeof getDailySessionCounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDailySessionCounts<TData = Awaited<ReturnType<typeof getDailySessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetDailySessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySessionCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the number of workout sessions per day over recent calendar weeks
 */

export function useGetDailySessionCounts<TData = Awaited<ReturnType<typeof getDailySessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetDailySessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailySessionCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDailySessionCountsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Return the current user's completed session counts per Monday-to-Sunday week.
 *
 * Weeks are ordered oldest first; a session counts towards the week it was started in.
 * @summary Get the number of completed workout sessions per week over recent calendar weeks
 */
export const getWeeklyCompletedSessionCounts = (
    params?: GetWeeklyCompletedSessionCountsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<number[]>(
      {url: `/api/v1/workout-sessions/weekly-counts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetWeeklyCompletedSessionCountsQueryKey = (params?: GetWeeklyCompletedSessionCountsParams,) => {
    return [
    `/api/v1/workout-sessions/weekly-counts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetWeeklyCompletedSessionCountsQueryOptions = <TData = Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError = ErrorType<HTTPValidationError>>(params?: GetWeeklyCompletedSessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWeeklyCompletedSessionCountsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>> = ({ signal }) => getWeeklyCompletedSessionCounts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWeeklyCompletedSessionCountsQueryResult = NonNullable<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>>
export type GetWeeklyCompletedSessionCountsQueryError = ErrorType<HTTPValidationError>


export function useGetWeeklyCompletedSessionCounts<TData = Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  GetWeeklyCompletedSessionCountsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklyCompletedSessionCounts<TData = Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetWeeklyCompletedSessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklyCompletedSessionCounts<TData = Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetWeeklyCompletedSessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the number of completed workout sessions per week over recent calendar weeks
 */

export function useGetWeeklyCompletedSessionCounts<TData = Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError = ErrorType<HTTPValidationError>>(
 params?: GetWeeklyCompletedSessionCountsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyCompletedSessionCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWeeklyCompletedSessionCountsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Return a single workout session owned by the current user.
 * @summary Get a workout session by ID
 */
export const getWorkoutSession = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/${sessionId}`, method: 'GET', signal
    },
      options);
    }




export const getGetWorkoutSessionQueryKey = (sessionId: string,) => {
    return [
    `/api/v1/workout-sessions/${sessionId}`
    ] as const;
    }


export const getGetWorkoutSessionQueryOptions = <TData = Awaited<ReturnType<typeof getWorkoutSession>>, TError = ErrorType<HTTPValidationError>>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkoutSessionQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutSession>>> = ({ signal }) => getWorkoutSession(sessionId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkoutSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkoutSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkoutSession>>>
export type GetWorkoutSessionQueryError = ErrorType<HTTPValidationError>


export function useGetWorkoutSession<TData = Awaited<ReturnType<typeof getWorkoutSession>>, TError = ErrorType<HTTPValidationError>>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutSession>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkoutSession<TData = Awaited<ReturnType<typeof getWorkoutSession>>, TError = ErrorType<HTTPValidationError>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutSession>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkoutSession<TData = Awaited<ReturnType<typeof getWorkoutSession>>, TError = ErrorType<HTTPValidationError>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a workout session by ID
 */

export function useGetWorkoutSession<TData = Awaited<ReturnType<typeof getWorkoutSession>>, TError = ErrorType<HTTPValidationError>>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkoutSessionQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Delete a workout session owned by the current user.
 * @summary Delete a workout session
 */
export const deleteWorkoutSession = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/workout-sessions/${sessionId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteWorkoutSessionMutationKey = () => ['deleteWorkoutSession'] as const;

export const getDeleteWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutSession>>, TError,DeleteWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutSession>>, TError,DeleteWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getDeleteWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkoutSession>>, DeleteWorkoutSessionMutationVariables> = (props) => {
          const {sessionId} = props ?? {};

          return  deleteWorkoutSession(sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkoutSession>>>

    export type DeleteWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type DeleteWorkoutSessionMutationVariables = {sessionId: string}

    /**
 * @summary Delete a workout session
 */
export const useDeleteWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutSession>>, TError,DeleteWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkoutSession>>,
        TError,
        DeleteWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteWorkoutSessionMutationOptions(options), queryClient);
    }
    /**
 * Update a workout session owned by the current user. Omitted fields are left unchanged.
 * @summary Update a workout session
 */
export const updateWorkoutSession = (
    sessionId: string,
    workoutSessionUpdate: WorkoutSessionUpdate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/${sessionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: workoutSessionUpdate, signal
    },
      options);
    }




export const getUpdateWorkoutSessionMutationKey = () => ['updateWorkoutSession'] as const;

export const getUpdateWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkoutSession>>, TError,UpdateWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkoutSession>>, TError,UpdateWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getUpdateWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkoutSession>>, UpdateWorkoutSessionMutationVariables> = (props) => {
          const {sessionId,data} = props ?? {};

          return  updateWorkoutSession(sessionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkoutSession>>>
    export type UpdateWorkoutSessionMutationBody = WorkoutSessionUpdate
    export type UpdateWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type UpdateWorkoutSessionMutationVariables = {sessionId: string;data: WorkoutSessionUpdate}

    /**
 * @summary Update a workout session
 */
export const useUpdateWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkoutSession>>, TError,UpdateWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateWorkoutSession>>,
        TError,
        UpdateWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateWorkoutSessionMutationOptions(options), queryClient);
    }
    /**
 * Start a new workout session copying the exercises of a template owned by the current user.
 * @summary Start a workout session from a template
 */
export const startWorkoutSession = (
    workoutSessionStart: WorkoutSessionStart,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: workoutSessionStart, signal
    },
      options);
    }




export const getStartWorkoutSessionMutationKey = () => ['startWorkoutSession'] as const;

export const getStartWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startWorkoutSession>>, TError,StartWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startWorkoutSession>>, TError,StartWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getStartWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startWorkoutSession>>, StartWorkoutSessionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  startWorkoutSession(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof startWorkoutSession>>>
    export type StartWorkoutSessionMutationBody = WorkoutSessionStart
    export type StartWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type StartWorkoutSessionMutationVariables = {data: WorkoutSessionStart}

    /**
 * @summary Start a workout session from a template
 */
export const useStartWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startWorkoutSession>>, TError,StartWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startWorkoutSession>>,
        TError,
        StartWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getStartWorkoutSessionMutationOptions(options), queryClient);
    }
    /**
 * Pause an in-progress workout session. Responds with 409 if it is completed or paused.
 * @summary Pause a workout session
 */
export const pauseWorkoutSession = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/${sessionId}/pause`, method: 'POST', signal
    },
      options);
    }




export const getPauseWorkoutSessionMutationKey = () => ['pauseWorkoutSession'] as const;

export const getPauseWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseWorkoutSession>>, TError,PauseWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof pauseWorkoutSession>>, TError,PauseWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getPauseWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pauseWorkoutSession>>, PauseWorkoutSessionMutationVariables> = (props) => {
          const {sessionId} = props ?? {};

          return  pauseWorkoutSession(sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PauseWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof pauseWorkoutSession>>>

    export type PauseWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type PauseWorkoutSessionMutationVariables = {sessionId: string}

    /**
 * @summary Pause a workout session
 */
export const usePauseWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseWorkoutSession>>, TError,PauseWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pauseWorkoutSession>>,
        TError,
        PauseWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getPauseWorkoutSessionMutationOptions(options), queryClient);
    }
    /**
 * Resume a paused workout session. Responds with 409 if it isn't paused.
 * @summary Resume a paused workout session
 */
export const resumeWorkoutSession = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/${sessionId}/resume`, method: 'POST', signal
    },
      options);
    }




export const getResumeWorkoutSessionMutationKey = () => ['resumeWorkoutSession'] as const;

export const getResumeWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeWorkoutSession>>, TError,ResumeWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resumeWorkoutSession>>, TError,ResumeWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getResumeWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resumeWorkoutSession>>, ResumeWorkoutSessionMutationVariables> = (props) => {
          const {sessionId} = props ?? {};

          return  resumeWorkoutSession(sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResumeWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof resumeWorkoutSession>>>

    export type ResumeWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type ResumeWorkoutSessionMutationVariables = {sessionId: string}

    /**
 * @summary Resume a paused workout session
 */
export const useResumeWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeWorkoutSession>>, TError,ResumeWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resumeWorkoutSession>>,
        TError,
        ResumeWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getResumeWorkoutSessionMutationOptions(options), queryClient);
    }
    /**
 * Mark a workout session owned by the current user as completed.
 *
 * A paused session must be resumed first; otherwise responds with 409.
 * @summary Complete a workout session
 */
export const completeWorkoutSession = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/${sessionId}/complete`, method: 'POST', signal
    },
      options);
    }




export const getCompleteWorkoutSessionMutationKey = () => ['completeWorkoutSession'] as const;

export const getCompleteWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeWorkoutSession>>, TError,CompleteWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof completeWorkoutSession>>, TError,CompleteWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getCompleteWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeWorkoutSession>>, CompleteWorkoutSessionMutationVariables> = (props) => {
          const {sessionId} = props ?? {};

          return  completeWorkoutSession(sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof completeWorkoutSession>>>

    export type CompleteWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type CompleteWorkoutSessionMutationVariables = {sessionId: string}

    /**
 * @summary Complete a workout session
 */
export const useCompleteWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeWorkoutSession>>, TError,CompleteWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeWorkoutSession>>,
        TError,
        CompleteWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getCompleteWorkoutSessionMutationOptions(options), queryClient);
    }
