/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  WorkoutSessionRead,
  WorkoutSessionStart
} from '../../model';

import { customInstance } from '../../http-client';
import type { ErrorType } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Return the current user's workout sessions that haven't been completed yet.
 * @summary List active workout sessions
 */
export const listActiveWorkoutSessions = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead[]>(
      {url: `/api/v1/workout-sessions/active`, method: 'GET', signal
    },
      options);
    }




export const getListActiveWorkoutSessionsQueryKey = () => {
    return [
    `/api/v1/workout-sessions/active`
    ] as const;
    }


export const getListActiveWorkoutSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListActiveWorkoutSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listActiveWorkoutSessions>>> = ({ signal }) => listActiveWorkoutSessions(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListActiveWorkoutSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listActiveWorkoutSessions>>>
export type ListActiveWorkoutSessionsQueryError = ErrorType<unknown>


export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listActiveWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List active workout sessions
 */

export function useListActiveWorkoutSessions<TData = Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listActiveWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListActiveWorkoutSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Return the current user's workout sessions that have been completed.
 * @summary List completed workout sessions
 */
export const listCompletedWorkoutSessions = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead[]>(
      {url: `/api/v1/workout-sessions/completed`, method: 'GET', signal
    },
      options);
    }




export const getListCompletedWorkoutSessionsQueryKey = () => {
    return [
    `/api/v1/workout-sessions/completed`
    ] as const;
    }


export const getListCompletedWorkoutSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompletedWorkoutSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>> = ({ signal }) => listCompletedWorkoutSessions(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCompletedWorkoutSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>>
export type ListCompletedWorkoutSessionsQueryError = ErrorType<unknown>


export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>,
          TError,
          Awaited<ReturnType<typeof listCompletedWorkoutSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List completed workout sessions
 */

export function useListCompletedWorkoutSessions<TData = Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompletedWorkoutSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCompletedWorkoutSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Start a new workout session copying the exercises of a template owned by the current user.
 * @summary Start a workout session from a template
 */
export const startWorkoutSession = (
    workoutSessionStart: WorkoutSessionStart,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: workoutSessionStart, signal
    },
      options);
    }




export const getStartWorkoutSessionMutationKey = () => ['startWorkoutSession'] as const;

export const getStartWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startWorkoutSession>>, TError,StartWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startWorkoutSession>>, TError,StartWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getStartWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startWorkoutSession>>, StartWorkoutSessionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  startWorkoutSession(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof startWorkoutSession>>>
    export type StartWorkoutSessionMutationBody = WorkoutSessionStart
    export type StartWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type StartWorkoutSessionMutationVariables = {data: WorkoutSessionStart}

    /**
 * @summary Start a workout session from a template
 */
export const useStartWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startWorkoutSession>>, TError,StartWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startWorkoutSession>>,
        TError,
        StartWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getStartWorkoutSessionMutationOptions(options), queryClient);
    }
    /**
 * Mark a workout session owned by the current user as completed.
 * @summary Complete a workout session
 */
export const completeWorkoutSession = (
    sessionId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutSessionRead>(
      {url: `/api/v1/workout-sessions/${sessionId}/complete`, method: 'POST', signal
    },
      options);
    }




export const getCompleteWorkoutSessionMutationKey = () => ['completeWorkoutSession'] as const;

export const getCompleteWorkoutSessionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeWorkoutSession>>, TError,CompleteWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof completeWorkoutSession>>, TError,CompleteWorkoutSessionMutationVariables, TContext> => {

const mutationKey = getCompleteWorkoutSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeWorkoutSession>>, CompleteWorkoutSessionMutationVariables> = (props) => {
          const {sessionId} = props ?? {};

          return  completeWorkoutSession(sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteWorkoutSessionMutationResult = NonNullable<Awaited<ReturnType<typeof completeWorkoutSession>>>

    export type CompleteWorkoutSessionMutationError = ErrorType<HTTPValidationError>
    export type CompleteWorkoutSessionMutationVariables = {sessionId: number}

    /**
 * @summary Complete a workout session
 */
export const useCompleteWorkoutSession = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeWorkoutSession>>, TError,CompleteWorkoutSessionMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeWorkoutSession>>,
        TError,
        CompleteWorkoutSessionMutationVariables,
        TContext
      > => {
      return useMutation(getCompleteWorkoutSessionMutationOptions(options), queryClient);
    }
