/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExerciseRead,
  ExerciseUpdate,
  HTTPValidationError,
  ListExercisesParams,
  PageExerciseRead
} from '../../model';

import { customInstance } from '../../http-client';
import type { ErrorType } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Return a page of the current user's exercises.
 * @summary List exercises
 */
export const listExercises = (
    params?: ListExercisesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PageExerciseRead>(
      {url: `/api/v1/exercises`, method: 'GET',
        params, signal
    },
      options);
    }




export const getListExercisesQueryKey = (params?: ListExercisesParams,) => {
    return [
    `/api/v1/exercises`, ...(params ? [params] : [])
    ] as const;
    }


export const getListExercisesQueryOptions = <TData = Awaited<ReturnType<typeof listExercises>>, TError = ErrorType<HTTPValidationError>>(params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExercisesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExercises>>> = ({ signal }) => listExercises(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListExercisesQueryResult = NonNullable<Awaited<ReturnType<typeof listExercises>>>
export type ListExercisesQueryError = ErrorType<HTTPValidationError>


export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListExercisesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExercises>>,
          TError,
          Awaited<ReturnType<typeof listExercises>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExercises>>,
          TError,
          Awaited<ReturnType<typeof listExercises>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List exercises
 */

export function useListExercises<TData = Awaited<ReturnType<typeof listExercises>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListExercisesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercises>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListExercisesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Update an exercise owned by the current user. Omitted fields are left unchanged.
 * @summary Update an exercise
 */
export const updateExercise = (
    exerciseId: number,
    exerciseUpdate: ExerciseUpdate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ExerciseRead>(
      {url: `/api/v1/exercises/${exerciseId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: exerciseUpdate, signal
    },
      options);
    }




export const getUpdateExerciseMutationKey = () => ['updateExercise'] as const;

export const getUpdateExerciseMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExercise>>, TError,UpdateExerciseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateExercise>>, TError,UpdateExerciseMutationVariables, TContext> => {

const mutationKey = getUpdateExerciseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateExercise>>, UpdateExerciseMutationVariables> = (props) => {
          const {exerciseId,data} = props ?? {};

          return  updateExercise(exerciseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof updateExercise>>>
    export type UpdateExerciseMutationBody = ExerciseUpdate
    export type UpdateExerciseMutationError = ErrorType<HTTPValidationError>
    export type UpdateExerciseMutationVariables = {exerciseId: number;data: ExerciseUpdate}

    /**
 * @summary Update an exercise
 */
export const useUpdateExercise = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExercise>>, TError,UpdateExerciseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateExercise>>,
        TError,
        UpdateExerciseMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateExerciseMutationOptions(options), queryClient);
    }
    /**
 * Delete an exercise owned by the current user.
 * @summary Delete an exercise
 */
export const deleteExercise = (
    exerciseId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/exercises/${exerciseId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteExerciseMutationKey = () => ['deleteExercise'] as const;

export const getDeleteExerciseMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExercise>>, TError,DeleteExerciseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteExercise>>, TError,DeleteExerciseMutationVariables, TContext> => {

const mutationKey = getDeleteExerciseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteExercise>>, DeleteExerciseMutationVariables> = (props) => {
          const {exerciseId} = props ?? {};

          return  deleteExercise(exerciseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteExerciseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExercise>>>

    export type DeleteExerciseMutationError = ErrorType<HTTPValidationError>
    export type DeleteExerciseMutationVariables = {exerciseId: number}

    /**
 * @summary Delete an exercise
 */
export const useDeleteExercise = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExercise>>, TError,DeleteExerciseMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteExercise>>,
        TError,
        DeleteExerciseMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteExerciseMutationOptions(options), queryClient);
    }
