/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  WorkoutTemplateCreate,
  WorkoutTemplateRead
} from '../../model';

import { customInstance } from '../../http-client';
import type { ErrorType } from '../../http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Return all of the current user's workout templates.
 * @summary List workout templates
 */
export const listWorkoutTemplates = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutTemplateRead[]>(
      {url: `/api/v1/workout-templates`, method: 'GET', signal
    },
      options);
    }




export const getListWorkoutTemplatesQueryKey = () => {
    return [
    `/api/v1/workout-templates`
    ] as const;
    }


export const getListWorkoutTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof listWorkoutTemplates>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkoutTemplatesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkoutTemplates>>> = ({ signal }) => listWorkoutTemplates(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkoutTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWorkoutTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkoutTemplates>>>
export type ListWorkoutTemplatesQueryError = ErrorType<unknown>


export function useListWorkoutTemplates<TData = Awaited<ReturnType<typeof listWorkoutTemplates>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutTemplates>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutTemplates<TData = Awaited<ReturnType<typeof listWorkoutTemplates>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutTemplates>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutTemplates<TData = Awaited<ReturnType<typeof listWorkoutTemplates>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workout templates
 */

export function useListWorkoutTemplates<TData = Awaited<ReturnType<typeof listWorkoutTemplates>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWorkoutTemplatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Create a new workout template owned by the current user.
 * @summary Create a workout template
 */
export const createWorkoutTemplate = (
    workoutTemplateCreate: WorkoutTemplateCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WorkoutTemplateRead>(
      {url: `/api/v1/workout-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: workoutTemplateCreate, signal
    },
      options);
    }




export const getCreateWorkoutTemplateMutationKey = () => ['createWorkoutTemplate'] as const;

export const getCreateWorkoutTemplateMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkoutTemplate>>, TError,CreateWorkoutTemplateMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkoutTemplate>>, TError,CreateWorkoutTemplateMutationVariables, TContext> => {

const mutationKey = getCreateWorkoutTemplateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkoutTemplate>>, CreateWorkoutTemplateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createWorkoutTemplate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateWorkoutTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkoutTemplate>>>
    export type CreateWorkoutTemplateMutationBody = WorkoutTemplateCreate
    export type CreateWorkoutTemplateMutationError = ErrorType<HTTPValidationError>
    export type CreateWorkoutTemplateMutationVariables = {data: WorkoutTemplateCreate}

    /**
 * @summary Create a workout template
 */
export const useCreateWorkoutTemplate = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkoutTemplate>>, TError,CreateWorkoutTemplateMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWorkoutTemplate>>,
        TError,
        CreateWorkoutTemplateMutationVariables,
        TContext
      > => {
      return useMutation(getCreateWorkoutTemplateMutationOptions(options), queryClient);
    }
