/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroupFactor } from './muscleGroupFactor';

/**
 * Payload for creating a new exercise.
 */
export interface ExerciseCreate {
  /** Exercise name. */
  name: string;
  /** Muscle group the exercise mainly targets. */
  primary_muscle_group: MuscleGroupFactor;
  /** Other muscle groups the exercise trains. Factors must not exceed the primary's. */
  secondary_muscle_groups?: MuscleGroupFactor[];
}
