/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';

/**
 * Payload for creating a new exercise.
 */
export interface ExerciseCreate {
  /** Exercise name. */
  name: string;
  /** Primary muscle group targeted. */
  muscle_group: MuscleGroup;
}
