/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroupFactor } from './muscleGroupFactor';

/**
 * An exercise as returned by the API.
 */
export interface ExerciseRead {
  /** Unique identifier. */
  id: string;
  /** Exercise name. */
  name: string;
  /** Muscle group the exercise mainly targets. */
  primary_muscle_group: MuscleGroupFactor;
  /** Other muscle groups the exercise trains, highest factor first. */
  secondary_muscle_groups: MuscleGroupFactor[];
  /** Id of the user who created this exercise, if any. */
  created_by?: string | null;
  /** When the exercise was created. */
  created_at: string;
}
