/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';

/**
 * An exercise as returned by the API.
 */
export interface ExerciseRead {
  /** Unique identifier. */
  id: number;
  /** Exercise name. */
  name: string;
  /** Primary muscle group targeted. */
  muscle_group: MuscleGroup;
  /** Id of the user who created this exercise, if any. */
  created_by?: number | null;
  /** When the exercise was created. */
  created_at: string;
}
