/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';

/**
 * Payload for updating an exercise. Omitted fields are left unchanged.
 */
export interface ExerciseUpdate {
  /** Exercise name. */
  name?: string | null;
  /** Primary muscle group targeted. */
  muscle_group?: MuscleGroup | null;
}
