/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export type GetDailySessionCountsParams = {
/**
 * How many calendar weeks to look at: 1 is only the current week, 4 the current and the three before.
 * @minimum 1
 */
weeks?: number;
};
