/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export type GetWeeklyMuscleGroupSetsParams = {
/**
 * Which calendar week to look at: 0 is the current week, 1 the last, 10 ten weeks ago.
 * @minimum 0
 */
weeks_ago?: number;
};
