/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Service health status.
 */
export interface HealthResponse {
  /** Overall service status. */
  status: string;
  /** Active environment name. */
  environment: string;
  /** API version. */
  version: string;
}
