/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export type Language = typeof Language[keyof typeof Language];


export const Language = {
  english: 'english',
  german: 'german',
} as const;
