/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export type ListExercisesParams = {
/**
 * Page number (1-indexed).
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page.
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
