/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';

/**
 * A muscle group an exercise trains, weighted by how strongly it trains it.
 */
export interface MuscleGroupFactor {
  /** Muscle group trained. */
  muscle_group: MuscleGroup;
  /**
     * How much one completed set counts towards this muscle group's weekly volume, with at most two decimal places.
     * @maximum 1
     * @exclusiveMinimum 0
     */
  factor: number;
}
