/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';

/**
 * Weighted number of completed sets for one muscle group.
 */
export interface MuscleGroupSetCount {
  /** Muscle group the sets were performed for. */
  muscle_group: MuscleGroup;
  /**
     * Completed sets, each weighted by the exercise's factor for this muscle group (e.g. a bench press set adds 1 to chest and 0.5 to triceps).
     * @minimum 0
     */
  completed_sets: number;
  /** Minimum effective volume: weekly sets needed to grow, if defined. */
  mev?: number | null;
  /** Maximum adaptive volume: weekly sets for optimal growth, if defined. */
  mav?: number | null;
  /** Maximum recoverable volume: weekly sets beyond which recovery suffers. */
  mrv?: number | null;
}
