/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export type MuscleGroup = typeof MuscleGroup[keyof typeof MuscleGroup];


export const MuscleGroup = {
  chest: 'chest',
  back: 'back',
  shoulders: 'shoulders',
  biceps: 'biceps',
  triceps: 'triceps',
  abs: 'abs',
  calves: 'calves',
  quads: 'quads',
  hamstrings: 'hamstrings',
} as const;
