/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { ExerciseRead } from './exerciseRead';

export interface PageExerciseRead {
  /** The items on this page. */
  items: ExerciseRead[];
  /** Total number of items across all pages. */
  total: number;
  /** Current page number (1-indexed). */
  page: number;
  /** Maximum number of items per page. */
  page_size: number;
  /** Total number of pages. */
  pages: number;
}
