/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A set within a session exercise, as submitted when updating a session.
 */
export interface SessionSetUpdate {
  /** Reps performed, once recorded. */
  reps?: number | null;
  /** Weight used, once recorded. */
  weight?: number | string | null;
  /** Whether this set has been marked done. */
  completed?: boolean;
}
