/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single performed set within a session exercise, as returned by the API.
 */
export interface SessionSetRead {
  /** Unique identifier. */
  id: number;
  /** Set order within the exercise, 1-indexed. */
  set_number: number;
  /** Reps performed. */
  reps: number;
  /** Weight used. */
  weight: string;
  /** Whether this set has been marked done. */
  completed: boolean;
}
