/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { SessionSetUpdate } from './sessionSetUpdate';

/**
 * An exercise slot within a session, as submitted when updating a session.
 */
export interface SessionExerciseUpdate {
  /** Id of the exercise in this slot. */
  exercise_id: string;
  /** Sets for this exercise, in order. */
  sets?: SessionSetUpdate[];
}
