/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroupFactor } from './muscleGroupFactor';
import type { SessionSetRead } from './sessionSetRead';

/**
 * An exercise slot within a workout session, as returned by the API.
 */
export interface SessionExerciseRead {
  /** Unique identifier. */
  id: string;
  /** Id of the exercise in this slot. */
  exercise_id: string;
  /** Exercise name. */
  name: string;
  /** Muscle group the exercise mainly targets. */
  primary_muscle_group: MuscleGroupFactor;
  /** Other muscle groups the exercise trains, highest factor first. */
  secondary_muscle_groups: MuscleGroupFactor[];
  /** Display order within the session, 1-indexed. */
  position: number;
  /** Sets performed for this exercise, in order. */
  sets: SessionSetRead[];
}
