/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';
import type { SessionSetRead } from './sessionSetRead';

/**
 * An exercise slot within a workout session, as returned by the API.
 */
export interface SessionExerciseRead {
  /** Unique identifier. */
  id: number;
  /** Id of the exercise in this slot. */
  exercise_id: number;
  /** Exercise name. */
  name: string;
  /** Primary muscle group targeted. */
  muscle_group: MuscleGroup;
  /** Display order within the session, 1-indexed. */
  position: number;
  /** Sets performed for this exercise, in order. */
  sets: SessionSetRead[];
}
