/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroupFactor } from './muscleGroupFactor';

/**
 * An exercise slot within a workout template, as returned by the API.
 */
export interface TemplateExerciseRead {
  /** Unique identifier. */
  id: string;
  /** Id of the exercise in this slot. */
  exercise_id: string;
  /** Exercise name. */
  name: string;
  /** Muscle group the exercise mainly targets. */
  primary_muscle_group: MuscleGroupFactor;
  /** Other muscle groups the exercise trains, highest factor first. */
  secondary_muscle_groups: MuscleGroupFactor[];
  /** Display order within the template, 1-indexed. */
  position: number;
  /** Number of planned sets. */
  set_count: number;
}
