/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Payload for one exercise slot within a new workout template.
 */
export interface TemplateExerciseCreate {
  /** Id of the exercise to add. */
  exercise_id: number;
  /**
     * Number of planned sets.
     * @exclusiveMinimum 0
     */
  set_count: number;
}
