/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroup } from './muscleGroup';

/**
 * An exercise slot within a workout template, as returned by the API.
 */
export interface TemplateExerciseRead {
  /** Unique identifier. */
  id: number;
  /** Id of the exercise in this slot. */
  exercise_id: number;
  /** Exercise name. */
  name: string;
  /** Primary muscle group targeted. */
  muscle_group: MuscleGroup;
  /** Display order within the template, 1-indexed. */
  position: number;
  /** Number of planned sets. */
  set_count: number;
}
