/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export type Theme = typeof Theme[keyof typeof Theme];


export const Theme = {
  dark: 'dark',
  light: 'light',
  system: 'system',
} as const;
