/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { Language } from './language';
import type { Theme } from './theme';

/**
 * Payload for updating a user's settings. Omitted fields are left unchanged.
 */
export interface UserSettingsUpdate {
  /** Preferred UI language. */
  language?: Language | null;
  /** Preferred UI theme. */
  theme?: Theme | null;
}
