/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A user as returned by the API. Never includes the password hash.
 */
export interface UserRead {
  /** User email address. */
  email: string;
  /**
     * Given name.
     * @maxLength 100
     */
  first_name: string;
  /**
     * Family name.
     * @maxLength 100
     */
  last_name: string;
  /** Unique identifier. */
  id: number;
  /** Whether the account is active. */
  is_active: boolean;
  /** Whether the account has elevated privileges. */
  is_superuser: boolean;
  /** When the account was created. */
  created_at: string;
}
