/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { Language } from './language';
import type { Theme } from './theme';

/**
 * A user's settings as returned by the API.
 */
export interface UserSettingsRead {
  /** Preferred UI language. */
  language: Language;
  /** Preferred UI theme. */
  theme: Theme;
}
