/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Credentials for signing in. Users authenticate by email.
 */
export interface UserLogin {
  /** User email address. */
  email: string;
  /** Plaintext password. */
  password: string;
}
