/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Payload for creating a user. The password is stored hashed, never in plaintext.
 */
export interface UserCreate {
  /** User email address. */
  email: string;
  /**
     * Given name.
     * @maxLength 100
     */
  first_name: string;
  /**
     * Family name.
     * @maxLength 100
     */
  last_name: string;
  /**
     * Plaintext password (min 8 characters).
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}
