/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
