/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { MuscleGroupSetCount } from './muscleGroupSetCount';

/**
 * Completed sets per muscle group for one calendar week (Monday to Sunday, UTC).
 */
export interface WeeklyMuscleGroupSets {
  /** Monday of the calendar week. */
  week_start: string;
  /** Sunday of the calendar week. */
  week_end: string;
  /** Completed set count for every muscle group, including those with 0. */
  muscle_groups: MuscleGroupSetCount[];
}
