/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { SessionExerciseRead } from './sessionExerciseRead';

/**
 * A workout session as returned by the API.
 */
export interface WorkoutSessionRead {
  /** Unique identifier. */
  id: string;
  /** Id of the user who owns this session. */
  user_id: string;
  /** Id of the template this session was started from, if any. */
  template_id?: string | null;
  /** Name of the template this session was started from, if any. */
  template_name?: string | null;
  /** When the session was started. */
  started_at: string;
  /** When the session was completed, if it has been. */
  completed_at?: string | null;
  /** Exercise slots, in order. */
  exercises: SessionExerciseRead[];
}
