/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Payload for starting a new workout session from a template.
 */
export interface WorkoutSessionStart {
  /** Id of the template to start a session from. */
  template_id: number;
}
