/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { TemplateExerciseCreate } from './templateExerciseCreate';

/**
 * Payload for updating a workout template. Omitted fields are left unchanged.
 *
 * When ``exercises`` is provided, it replaces the entire set of slots;
 * position is assigned from list order, so reordering is done by
 * resubmitting the list in the desired order.
 */
export interface WorkoutTemplateUpdate {
  /** Template name. */
  name?: string | null;
  /** Replacement exercise slots, in order. */
  exercises?: TemplateExerciseCreate[] | null;
}
