/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { SessionExerciseUpdate } from './sessionExerciseUpdate';

/**
 * Payload for updating a workout session. Omitted fields are left unchanged.
 *
 * ``template_id`` and ``completed_at`` may be set to ``null`` explicitly to
 * clear them (e.g. reopening a completed session). When ``exercises`` is
 * provided, it replaces the entire set of exercise slots and their sets;
 * ``position`` and ``set_number`` are assigned from list order.
 */
export interface WorkoutSessionUpdate {
  /** Id of the template this session is associated with. */
  template_id?: string | null;
  /** When the session was started. */
  started_at?: string | null;
  /** When the session was completed. */
  completed_at?: string | null;
  /** Replacement exercise slots, in order. */
  exercises?: SessionExerciseUpdate[] | null;
}
