/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { TemplateExerciseCreate } from './templateExerciseCreate';

/**
 * Payload for creating a new workout template.
 */
export interface WorkoutTemplateCreate {
  /**
     * Template name.
     * @minLength 1
     */
  name: string;
  /**
     * Exercise slots to add, in order.
     * @minItems 1
     */
  exercises: TemplateExerciseCreate[];
}
