/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Web App Template API
 * Backend API for the web app template.
 * OpenAPI spec version: 0.1.0
 */
import type { TemplateExerciseRead } from './templateExerciseRead';

/**
 * A workout template as returned by the API.
 */
export interface WorkoutTemplateRead {
  /** Unique identifier. */
  id: string;
  /** Id of the user who owns this template. */
  user_id: string;
  /** Template name. */
  name: string;
  /** When the template was created. */
  created_at: string;
  /** Exercise slots, in order. */
  exercises: TemplateExerciseRead[];
}
